experiment_name: 'chameleon_clip_vit_p16'

data:
  path: src/data/chameleon
  batch_size: 96
  num_workers: 4
  image_size: 224
  shuffle: true
  validation_split: 0.2
  test_split: 0.1
  

model:
  name: 'vit_base_patch16_clip_224'
  pretrained: true
  num_classes: 2

training:
  optimizer_type: 'adamw'
  learning_rate: 1e-5
  weight_decay: 5e-4
  min_epochs: 3
  max_epochs: 5
  lr_monitoring: true
  early_stopping:
    enabled: true
    patience: 3
    monitor: 'val_loss'
    mode: 'min'

seed: 7643
logging:
  type: 'CSV'
  checkpoint_dir: src/checkpoints
  logs_dir: src/logs
