experiment_name: 'chameleon_convnext_tiny'

data:
  path: src/data/chameleon
  # training_path:
  # validation_path:
  # test_path:
  batch_size: 96
  num_workers: 4
  validation_split: 0.2
  test_split: 0.1
  image_size: 224
  shuffle: true

model:
  name: 'convnext_tiny'
  pretrained: true
  num_classes: 2

training:
  optimizer_type: 'adamw'
  # scheduler_type: 'cosine'
  learning_rate: 1e-4
  # step_size: 1
  # gamma: 0.5
  weight_decay: 0.0001
  min_epochs: 3
  max_epochs: 5
  lr_monitoring: true
  early_stopping:
    enabled: true
    patience: 3
    monitor: 'val_loss'
    mode: 'min'

seed: 7643
logging:
  type: 'CSV'
  checkpoint_dir: src/checkpoints
  logs_dir: src/logs
