data:
  path: ./data/mnist
  batch_size: 128
  num_workers: 4
  validation_split: 0.2
  transforms:
    - normalize
    - flatten

model:
  name: 'vit_small_patch16_224'
  pretrained: true
  num_classes: 

training:
  optimizer_type: 'adamw'
  scheduler_type: 'cosine_annealing'
  learning_rate: 0.001
  weight_decay: 0.0001
  min_epochs: 5
  max_epochs: 50

seed: 7643
device: 'cuda'
logging:
  type: 'CSV'
  save_checkpoint: true
  checkpoint_path: ./checkpoints
  logs_path: ./logs
